- hosts: all
  become: true
  tasks:

  - name: Update and Upgrade the servers
    apt:
      update_cache: yes
      upgrade: yes

  - name : Install apache2
    apt:
      name:
        - apache2
      state: latest

  - name: Set the timezone to lagos
    timezone: name=Africa/Lagos

  - name: Print hostname on servers
    shell: echo "<h1>This is my server name $(hostname -f)</h1>" > /var/www/html/index.html

  - name: restart apache2
    service:
      name: apache2
      state: restarted
